name: Deploy Database Migrations

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Updated to latest LTS version

    - name: Install dependencies
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::381491878469:role/backend_pipeline_assume_role
        aws-region: ap-southeast-1

    - name: Run Sequelize migrations
      env:
        NODE_ENV: staging
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx sequelize-cli db:migrate
